import { useEffect } from 'react';
import './Article.css'


function EnvironmentArticle() {
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  return (
    <div className="article">
      <header>
          <h1>Driving Green and Reducing Carbon Emissions</h1>
      </header>
      <article>
          <p>The global community is facing a critical challenge in the form of climate change. One of the major contributors to this crisis is the transportation sector, particularly the emissions generated by individual vehicles. Fortunately, innovative solutions are emerging to address this problem. hitchHype not only makes transportation more efficient and affordable but also plays a crucial role in reducing our carbon footprint. </p>

          <h3>1. Shared Rides, Reduced Emissions</h3>
          <p>hitchHype, at its core, encourages ride-sharing. When multiple passengers share a single vehicle for a common destination, it significantly reduces the number of vehicles on the road. Fewer vehicles mean fewer emissions, as each passenger contributes to the reduction of carbon emissions by decreasing the number of individual vehicles emitting harmful pollutants.</p>

          <h3>2. Fewer Idle Cars</h3>
          <p>Idle cars are a significant contributor to carbon emissions. Many vehicles spend most of their time parked and unused. hitchHype helps to put those idle cars to good use by connecting drivers with passengers who need a ride in the same direction. This results in fewer idle vehicles on the road and, subsequently, a reduction in emissions.</p>

          <h3>3. Community Building and Carpooling Culture</h3>
          <p>hitchHype fosters a sense of community and promotes a carpooling culture. By connecting people who might not have met otherwise, it encourages a shift towards sharing rides as a way of life. The stronger the carpooling culture becomes, the more vehicles will be off the road, leading to a substantial reduction in carbon emissions.</p>

          <p>The hitchHype carpooling app isn't just about sharing rides; it's about making environmentally conscious choices that have a positive impact on our planet. By reducing the number of vehicles on the road, optimizing routes, and promoting eco-friendly transportation options, hitchHype is actively contributing to a reduction in carbon emissions. Moreover, it's building a community of individuals who are committed to making greener choices and redefining the way we think about transportation. As we collectively strive to combat climate change, hitchHype is proving to be a valuable ally in our efforts to protect the environment for future generations. Join the ride, reduce your carbon footprint, and be part of the solution with hitchHype.</p>
      </article>
    </div>
  );
}

export default EnvironmentArticle;